"""
core.par_parser
===============
Robust parser for TEMPO/TEMPO2-style `.par` files.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
import re


@dataclass
class ParParseReport:
    lines_read: int = 0
    lines_used: int = 0
    invalid_parameters: int = 0
    incomplete_glitches: int = 0
    glitches_found: int = 0
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors

    # Backward-compatible Spanish aliases used by older UI code.
    @property
    def lineas_leidas(self) -> int:
        return self.lines_read

    @property
    def lineas_validas(self) -> int:
        return self.lines_used

    @property
    def parametros_invalidos(self) -> int:
        return self.invalid_parameters

    @property
    def glitches_incompletos(self) -> int:
        return self.incomplete_glitches

    @property
    def glitches_encontrados(self) -> int:
        return self.glitches_found

    @property
    def advertencias(self) -> list[str]:
        return self.warnings

    @property
    def errores(self) -> list[str]:
        return self.errors


_GLITCH_PATTERN = re.compile(r"^(GLEP|GLPH|GLF0|GLF1|GLF2|GLF0D|GLTD)_(\d+)$", re.IGNORECASE)


def _read_lines(source: str | bytes | Path) -> list[str]:
    if isinstance(source, bytes):
        return source.decode("utf-8", errors="replace").splitlines()
    path = Path(source)
    return path.read_text(encoding="utf-8", errors="replace").splitlines()


def _parse_value(value: str) -> Any:
    if ":" in value:
        return value
    try:
        return float(value)
    except ValueError:
        return value


def parse_par(source: str | bytes | Path) -> tuple[dict[str, Any], ParParseReport]:
    report = ParParseReport()
    params: dict[str, Any] = {}
    glitches_raw: dict[int, dict[str, float]] = {}

    for raw_line in _read_lines(source):
        report.lines_read += 1
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("C "):
            continue

        # Remove inline comments while preserving sexagesimal coordinates.
        if " #" in line:
            line = line.split(" #", 1)[0].strip()

        parts = line.split()
        if len(parts) < 2:
            continue

        key = parts[0].upper()
        value = parts[1]
        report.lines_used += 1

        match = _GLITCH_PATTERN.match(key)
        if match:
            gl_key = match.group(1).upper()
            gl_idx = int(match.group(2))
            try:
                glitches_raw.setdefault(gl_idx, {})[gl_key] = float(value)
            except ValueError:
                report.invalid_parameters += 1
                report.warnings.append(f"Could not parse {key}={value!r} as a floating-point value.")
            continue

        params[key] = _parse_value(value)

    glitches: list[dict[str, float]] = []
    for idx in sorted(glitches_raw):
        glitch = glitches_raw[idx]
        if "GLEP" not in glitch:
            report.incomplete_glitches += 1
            report.warnings.append(f"Glitch {idx} has no GLEP epoch. It was kept but may not affect the model.")
        glitches.append(glitch)

    report.glitches_found = len(glitches)
    params["glitches"] = glitches

    if "F0" not in params:
        report.errors.append("Required spin parameter F0 is missing.")
    if "PEPOCH" not in params:
        report.errors.append("Required reference epoch PEPOCH is missing.")

    return params, report


def serialize_par(params: dict[str, Any]) -> str:
    ordered_keys = [
        "PSRJ", "PSR", "RAJ", "DECJ", "F0", "F1", "F2", "F3", "PEPOCH",
        "DM", "DM1", "DM2", "EPHEM", "CLK", "UNITS", "TIMEEPH", "START", "FINISH",
    ]

    lines = ["# Generated by PulsarLab", ""]
    written: set[str] = set()

    for key in ordered_keys:
        if key in params and key != "glitches":
            value = params[key]
            if isinstance(value, float):
                lines.append(f"{key:<18} {value:.16g}")
            else:
                lines.append(f"{key:<18} {value}")
            written.add(key)

    for key, value in params.items():
        if key in written or key == "glitches":
            continue
        if isinstance(value, float):
            lines.append(f"{key:<18} {value:.16g}")
        else:
            lines.append(f"{key:<18} {value}")

    glitches = params.get("glitches", [])
    if glitches:
        lines.append("")
        for idx, glitch in enumerate(glitches, start=1):
            for key in ["GLEP", "GLPH", "GLF0", "GLF1", "GLF2", "GLF0D", "GLTD"]:
                if key in glitch:
                    lines.append(f"{key}_{idx:<15} {float(glitch[key]):.16g}")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"
